services:
  - type: web
    name: cloud-log-backend
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://Sinchana:<NETFLIX>@cluster0.wviwovk.mongodb.net/?appName=Cluster0
        sync: false
      - key: CLIENT_URL
        fromService:
          name: cloud-log-frontend
          type: web
          property: host
    healthCheckPath: /api/health

  - type: web
    name: cloud-log-frontend
    runtime: static
    rootDir: frontend
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          name: cloud-log-backend
          type: web
          property: host
